name: Build and Release

on:
  push:
    branches:
      - workflowTest

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build .lib file
      run: |
        msbuild /p:Configuration=Release /t:RegistryHelper /p:Platform=x64 RegistryHelper.sln

    - name: Upload to Release
      uses: actions/upload-artifact@v2
      with:
        name: lib-artifact
        path: |
          x64/Release/RegistryHelper.lib
          x64/Release/RegistryHelper.pdb

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git tag -a v1.0.0 -m "Version 1.0.0"
        git push origin v1.0.0

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v0
      with:
        gh-version: 2

    - name: Display release version
      run: |
        echo "Release version: v1.0.0"

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          x64/Release/*
        data: |
          { "version": "v1.0.0" }

    - name: Comment on Release
      run: |
        echo "Release version: v1.0.0" > release_message.txt
        cat release_message.txt
      env:
        RELEASE_VERSION: v1.0.0
        
    - name: Comment on Release
      run: |
        gh release upload ${{ github.repository }} ${{ steps.create_release.outputs.id }} release_message.txt --title "Release Notes"
